name: Build and Test HAProxy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and install Cygwin
        run: |
          mkdir c:\cygwin64
          cd c:\cygwin64
          Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile setup-x86_64.exe
          .\setup-x86_64.exe -q -P wget -P gcc-g++ -P make -P libssl-devel -P zlib-devel -P ldd
          .\Cygwin.bat

      - name: Download latest HAProxy source code
        run: |
          Invoke-WebRequest -Uri $(curl -s https://www.haproxy.org/download/ | Select-String -Pattern 'href="haproxy-.*tar.gz"' | ForEach-Object { $_ -replace '^.*href="([^"]+)".*$', '$1' }) -OutFile haproxy-latest.tar.gz
          tar xzvf haproxy-latest.tar.gz
          rm -rf ./haproxy-latest.tar.gz
          cd haproxy-*/

      - name: Build HAProxy
        run: |
          make TARGET=cygwin USE_OPENSSL=1 USE_ZLIB=1

      - name: Copy HAProxy executable and dependencies
        run: |
          dependencies=$(ldd ./haproxy.exe | awk '{print $3}')
          mkdir -p /cygdrive/c/haproxy-latest
          cp ./haproxy.exe /cygdrive/c/haproxy-latest
          for dep in $dependencies; do
              cp "$dep" /cygdrive/c/haproxy-latest
          done
          cd ..
          rm -rf ./haproxy-*/
          exit

      - name: Test HAProxy
        run: |
          cd C:\haproxy-latest
          haproxy.exe -v
