name: Build and Test HAProxy 3.0

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and install Cygwin
        run: |
          mkdir c:\cygwin64
          cd c:\cygwin64
          Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile setup-x86_64.exe
          .\setup-x86_64.exe --root c:\cygwin64 -q -P wget -P gcc-g++ -P make -P libssl-devel -P zlib-devel -P ldd -s https://linorg.usp.br/cygwin/

      - name: Open Cygwin
        run: |
          cd c:\cygwin64
          dir
          c:\cygwin64\bin\bash.exe --login

      - name: Download 3.0 HAProxy source code
        run: |
          wget https://www.haproxy.org/download/3.0/src/devel/haproxy-3.0-dev1.tar.gz
          tar xzvf haproxy-3.0-dev1.tar.gz
          rm -rf ./haproxy-3.0-dev1.tar.gz 
          cd haproxy-3.0-dev1
          
      - name: Build HAProxy
        run: |
          make TARGET=cygwin USE_OPENSSL=1 USE_ZLIB=1

      - name: Copy HAProxy executable and dependencies
        run: |
          dependencies=$(ldd ./haproxy.exe | awk '{print $3}')
          mkdir -p /cygdrive/c/haproxy-3.0
          cp ./haproxy.exe /cygdrive/c/haproxy-3.0
          for dep in $dependencies; do
              cp "$dep" /cygdrive/c/haproxy-3.0
          done
          cd ..
          rm -rf ./haproxy-*/
          exit

      - name: Test HAProxy
        run: |
          cd C:\haproxy-3.0
          haproxy.exe -v
